use crate::db::filters::{FilterRule, FilterCondition, FilterAction};

/// Returns true if the rule can be fully represented as a Sieve script.
/// Rules with `body` conditions or `tag` actions must stay in the IDLE path.
pub fn is_sieve_capable(rule: &FilterRule) -> bool {
    let bad_condition = rule.conditions.iter().any(|c| c.field == "body");
    let bad_action = rule.actions.iter().any(|a| a.action_type == "tag");
    !bad_condition && !bad_action
}

/// Generate a Sieve script from all enabled, Sieve-capable rules.
pub fn generate_sieve_script(rules: &[FilterRule]) -> String {
    let capable: Vec<&FilterRule> = rules
        .iter()
        .filter(|r| r.enabled && is_sieve_capable(r))
        .collect();

    if capable.is_empty() {
        return "# rav-filters\n".to_string();
    }

    let needs_fileinto = capable.iter().any(|r| {
        r.actions.iter().any(|a| a.action_type == "move" || a.action_type == "delete")
    });
    let needs_imap4flags = capable.iter().any(|r| {
        r.actions.iter().any(|a| a.action_type == "mark_read" || a.action_type == "mark_starred")
    });

    let mut out = String::new();

    let mut exts: Vec<&str> = Vec::new();
    if needs_fileinto { exts.push("fileinto"); }
    if needs_imap4flags { exts.push("imap4flags"); }

    if !exts.is_empty() {
        out.push_str("require [");
        let quoted: Vec<String> = exts.iter().map(|e| format!("\"{}\"", e)).collect();
        out.push_str(&quoted.join(", "));
        out.push_str("];\n\n");
    }

    for rule in &capable {
        let conditions: Vec<String> = rule.conditions
            .iter()
            .filter_map(condition_to_sieve)
            .collect();

        if conditions.is_empty() {
            continue;
        }

        let test = if conditions.len() == 1 {
            format!("allof({})", conditions[0])
        } else if rule.match_mode == "any" {
            format!("anyof({})", conditions.join(", "))
        } else {
            format!("allof({})", conditions.join(", "))
        };

        out.push_str(&format!("if {} {{\n", test));

        for action in &rule.actions {
            if let Some(line) = action_to_sieve(action) {
                out.push_str(&format!("    {}\n", line));
            }
        }

        if rule.stop_processing {
            out.push_str("    stop;\n");
        }

        out.push_str("}\n\n");
    }

    out
}

fn field_to_header(field: &str) -> Option<&'static str> {
    match field {
        "from" => Some("From"),
        "to" => Some("To"),
        "cc" => Some("Cc"),
        "subject" => Some("Subject"),
        _ => None,
    }
}

/// Escape a value for use inside a Sieve quoted string.
/// One script carries everything, because Dovecot activates exactly one per
/// user: the filter rules first, then the out-of-office responder.
pub fn generate_script(
    rules: &[FilterRule],
    vacation: Option<&crate::db::vacation::VacationResponder>,
) -> String {
    let rules_part = generate_sieve_script(rules);
    let Some(v) = vacation.filter(|v| v.enabled) else {
        return rules_part;
    };

    // Sieve counts in whole days. Round up so a shorter interval never becomes
    // "reply to everything", and never go below the one day Sieve allows.
    let days = v.reply_interval_hours.div_euclid(24).max(0)
        + i64::from(v.reply_interval_hours.rem_euclid(24) > 0);
    let days = days.max(1);

    let mut guards = Vec::new();
    if let Some(ref start) = v.start_date {
        guards.push(format!(
            "currentdate :value \"ge\" \"date\" \"{}\"",
            escape_sieve(start)
        ));
    }
    if let Some(ref end) = v.end_date {
        guards.push(format!(
            "currentdate :value \"le\" \"date\" \"{}\"",
            escape_sieve(end)
        ));
    }

    let mut extensions = vec!["\"vacation\""];
    if !guards.is_empty() {
        extensions.extend(["\"date\"", "\"relational\""]);
    }

    let action = format!(
        "vacation :days {days} :subject \"{}\" text:\n{}\n.\n;",
        escape_sieve(&v.subject),
        stuff_dots(&v.body),
    );

    let block = if guards.is_empty() {
        action
    } else {
        format!(
            "if allof ({}) {{\n  {action}\n}}",
            guards.join(",\n          ")
        )
    };

    format!(
        "{rules_part}\n# --- out of office (generated by Altacee Mail) ---\nrequire [{}];\n{block}\n",
        extensions.join(", ")
    )
}

/// In a `text:` literal a line that is a single dot ends it, so any leading dot
/// is doubled — the same rule SMTP uses.
fn stuff_dots(body: &str) -> String {
    body.lines()
        .map(|l| if l.starts_with('.') { format!(".{l}") } else { l.to_string() })
        .collect::<Vec<_>>()
        .join("\n")
}

fn escape_sieve(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Escape a value for use in a Sieve :matches glob (additionally escapes * and ?).
fn escape_sieve_glob(s: &str) -> String {
    escape_sieve(s).replace('*', "\\*").replace('?', "\\?")
}

fn condition_to_sieve(cond: &FilterCondition) -> Option<String> {
    match cond.field.as_str() {
        "has_attachment" => {
            return Some("header :contains \"Content-Type\" \"multipart/\"".to_string());
        }
        "is_reply" => {
            return Some("exists \"In-Reply-To\"".to_string());
        }
        "size" => {
            let n: u64 = cond.value.parse().ok()?;
            return match cond.op.as_str() {
                "greater_than" => Some(format!("size :over {}", n)),
                "less_than" => Some(format!("size :under {}", n)),
                _ => None,
            };
        }
        _ => {}
    }

    let header = field_to_header(&cond.field)?;
    let v = &cond.value;

    let test = match cond.op.as_str() {
        "contains" => format!("header :contains \"{}\" \"{}\"", header, escape_sieve(v)),
        "not_contains" => format!("not header :contains \"{}\" \"{}\"", header, escape_sieve(v)),
        "equals" => format!("header :is \"{}\" \"{}\"", header, escape_sieve(v)),
        "not_equals" => format!("not header :is \"{}\" \"{}\"", header, escape_sieve(v)),
        "starts_with" => format!("header :matches \"{}\" \"{}*\"", header, escape_sieve_glob(v)),
        "ends_with" => format!("header :matches \"{}\" \"*{}\"", header, escape_sieve_glob(v)),
        _ => return None,
    };

    Some(test)
}

fn action_to_sieve(action: &FilterAction) -> Option<String> {
    match action.action_type.as_str() {
        "mark_read" => Some("addflag \"\\\\Seen\";".to_string()),
        "mark_starred" => Some("addflag \"\\\\Flagged\";".to_string()),
        "move" => {
            let folder = action.action_value.as_deref()?;
            Some(format!("fileinto \"{}\";", escape_sieve(folder)))
        }
        "delete" => Some("fileinto \"Trash\";".to_string()),
        "forward" => {
            let addr = action.action_value.as_deref()?;
            Some(format!("redirect \"{}\";", escape_sieve(addr)))
        }
        _ => None,
    }
}

#[cfg(test)]
mod vacation_tests {
    use super::*;
    use crate::db::vacation::VacationResponder;

    fn responder() -> VacationResponder {
        VacationResponder {
            enabled: true,
            subject: "Out of office".to_string(),
            body: "Back on Monday.".to_string(),
            start_date: None,
            end_date: None,
            reply_interval_hours: 24,
        }
    }

    #[test]
    fn disabled_responder_emits_no_vacation_rule() {
        let mut v = responder();
        v.enabled = false;
        let script = generate_script(&[], Some(&v));
        assert!(!script.contains("vacation"), "got: {script}");
    }

    #[test]
    fn enabled_responder_requires_and_emits_vacation() {
        let script = generate_script(&[], Some(&responder()));
        assert!(script.contains("require [\"vacation\"]"), "got: {script}");
        assert!(script.contains(":days 1"), "got: {script}");
        assert!(script.contains(":subject \"Out of office\""), "got: {script}");
        assert!(script.contains("Back on Monday."), "got: {script}");
    }

    #[test]
    fn dates_become_currentdate_guards() {
        let mut v = responder();
        v.start_date = Some("2026-09-20".to_string());
        v.end_date = Some("2026-09-30".to_string());
        let script = generate_script(&[], Some(&v));
        assert!(
            script.contains("currentdate :value \"ge\" \"date\" \"2026-09-20\""),
            "got: {script}"
        );
        assert!(
            script.contains("currentdate :value \"le\" \"date\" \"2026-09-30\""),
            "got: {script}"
        );
        assert!(script.contains("\"date\""), "the date extension must be required: {script}");
    }

    #[test]
    fn hours_round_up_to_whole_days_and_never_below_one() {
        let mut v = responder();
        v.reply_interval_hours = 30;
        assert!(generate_script(&[], Some(&v)).contains(":days 2"));
        v.reply_interval_hours = 1;
        assert!(generate_script(&[], Some(&v)).contains(":days 1"));
        v.reply_interval_hours = 0;
        assert!(generate_script(&[], Some(&v)).contains(":days 1"));
    }

    #[test]
    fn quotes_in_the_subject_are_escaped() {
        let mut v = responder();
        v.subject = "Re: \"urgent\"".to_string();
        let script = generate_script(&[], Some(&v));
        assert!(script.contains(":subject \"Re: \\\"urgent\\\"\""), "got: {script}");
    }

    #[test]
    fn a_body_line_that_is_a_lone_dot_is_stuffed() {
        let mut v = responder();
        v.body = "first\n.\nlast".to_string();
        let script = generate_script(&[], Some(&v));
        assert!(
            script.contains("\n..\n"),
            "a lone dot would end the literal early: {script}"
        );
    }

    #[test]
    fn filter_rules_still_come_through_unchanged() {
        let plain = generate_sieve_script(&[]);
        let combined = generate_script(&[], None);
        assert_eq!(plain, combined);
    }
}
